skills = [
    "python",
    "java",
    "c++",
    "c",
    "javascript",
    "typescript",
    "react",
    "angular",
    "nodejs",
    "node.js",
    "express",
    "mongodb",
    "mysql",
    "postgresql",
    "html",
    "css",
    "bootstrap",
    "machine learning",
    "deep learning",
    "tensorflow",
    "pytorch",
    "nlp",
    "data structures",
    "algorithms",
    "git",
    "github",
    "docker",
    "rest api",
    "flask",
    "django"
]